apisix:
  node_listen: 9080
  enable_ipv6: false

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    allow_admin:
      - 0.0.0.0/0
    admin_listen:
      port: 9180
  etcd:
    host:
      - http://etcd:2379
    prefix: /apisix

plugins:
  - real-ip
  - ai-proxy-multi
  - proxy-rewrite
  - response-rewrite
  - limit-req
  - limit-count
  - key-auth
  - cors
  - prometheus
  - http-logger

plugin_attr:
  ai-proxy-multi:
    log_request_body: false
    log_response_body: false
